stages:
- test

language: python
sudo: false
python:
- '3.4.3'
- '3.4'
- '3.5.2'
- '3.5'
- '3.6'

matrix:
    allow_failures:
        - python: '3.6'

install: pip install tox coveralls
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success: coveralls
